# Generated by Django 5.1.7 on 2025-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluída', 'Concluída')], default='pendente', max_length=13),
        ),
    ]
